# Generated by Django 3.0.5 on 2020-04-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateField(max_length=10)),
                ('description', models.CharField(max_length=1000)),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
